### ISSUE TITLE
Course URL not working

### ISSUE THREAD

**Issue by jaamaalxyz** [howtocode-com-bd/ds.howtocode.com.bd#5]
Please update the course URL in the about section of this repo to `https://ds.howtocode.dev/` instead of `http://ds.howtocode.com.bd/`.

![image](https://user-images.githubusercontent.com/20262255/105621750-3fb47200-5e35-11eb-9112-e72cb8f8964c.png)

**Comment by howtocode-dev** [comment]
thanks for pointing out. fixed!
